name: Ramim IPTV Self-Healing Engine

on:
  schedule:
    - cron: '0 18 * * *' # বাংলাদেশ সময় ঠিক রাত ১২:০০ টায় (18:00 UTC) রান হবে
  workflow_dispatch: # এটি থাকার কারণে আপনি চাইলে যেকোনো সময় ম্যানুয়ালিও রান করতে পারবেন

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests urllib3

      - name: Execute Ramim Engine
        env:
          IPTV_SOURCES: ${{ secrets.IPTV_SOURCES }}
        run: python updater.py

      - name: Commit and Push Updates
        run: |
          git config --global user.name "ramim247"
          git config --global user.email "ramimcomputer247@gmail.com"
          git add master.m3u8 death.m3u8 dead_tracker.json
          git diff-index --quiet HEAD || git commit -m "RAMIM Engine Midnight Auto-Refreshed [$(date)]"
          git push
